version: '3'

services:
  rdb:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ~/.dockerdata/goteam/rdb/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_USER_PASSWORD: test
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/.dockerdata/goteam/nosql/mongo:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ~/.dockerdata/goteam/nosql/redis:/data
